### ISSUE TITLE
Add `nginx` reverse proxy integration

### ISSUE THREAD

**Issue by acouvreur** [acouvreur/sablier#118]
**Describe the reverse proxy you'd like**
Nginx reverse proxy

**Does the reverse proxy provides middleware/module/extension support**
Yes through 3rd party modules.

- https://www.nginx.com/resources/wiki/modules/
- http://nginx.org/en/docs/dev/development_guide.html

> Common Pitfalls
> Writing a C module
> 
> The most common pitfall is an attempt to write a full-fledged C module when it can be avoided. In most cases your task can be accomplished by creating a proper configuration. If writing a module is inevitable, try to make it as small and simple as possible. For example, a module can only export some [variables](http://nginx.org/en/docs/dev/development_guide.html#http_variables).
> 
> Before starting a module, consider the following questions:
> 
>    Is it possible to implement a desired feature using already [available modules](http://nginx.org/en/docs/index.html)?
>    Is it possible to solve an issue using built-in scripting languages, such as [Perl](http://nginx.org/en/docs/http/ngx_http_perl_module.html) or [njs](http://nginx.org/en/docs/njs/index.html)?

- http://nginx.org/en/docs/njs/index.html

**Additional context**

We need to be able to create a module that can do the following op

![](https://github.com/acouvreur/sablier/raw/main/docs/img/reverse-proxy-integration.png)

So be able to intercept a packet, and either return custom data or proxy pass depending on the subrequest result.

**Comment by skurfuerst** [comment]
Hey @acouvreur ,

You might not need to develop a new module; it might be enough to use https://nginx.org/en/docs/http/ngx_http_auth_request_module.html - this is the basis of https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#external-authentication

If this is not enough, you could use openresty (though the former is supported in nginx ingress in K8S already).

Maybe this helps as an idea :) if you need any help let me know; I have very long waited for a project such as yours and would love to have it working with nginx ingress in k8s :) 

All the best,
Sebastian

**Comment by acouvreur** [comment]
Thank you very much @skurfuerst.

I've been looking to many ways of not doing my own nginx module.
Right now I'm looking at every opportunity for me, not to.

I've already looked over the auth module, but my first impression was that it wasn't possible for few reasons.

- I need to be able to serve a response from Sablier when the underlying service is down
- The redirection is based on a header `X-Sablier-Session-Status`, you can see for yourself in the Traefik integration 

https://github.com/acouvreur/sablier/blob/bce92cbec07fc62a07eb0b088b830cf1c5a16023/plugins/traefik/main.go#L40

- I need to be able to set some configuration on the proxy config to customize the strategies (e.g. traefik middleware config)
![image](https://user-images.githubusercontent.com/22034450/205400375-645b7ffa-3806-4229-8016-da1ef2be6562.png)

So first, maybe I should have a clear intent of what my ideal nginx config would look like. I thought of something close to this:

```nginx
  server {
    listen     8000;

    sablier_url http://sablier:10000;
    sablier_session_duration 1m

    location /dynamic/whoami {
      sablier_names whoami
      sablier_dynamic_display_name Dynamic

      proxy_pass http://whoami/$1;
    }

    location /blocking/whoami {
      sablier_names whoami
      sablier_blocking_timeout 1m

      proxy_pass http://whoami/$1;
    }
    }
  }
```

But I'm sure there would be better way of representing this. As the `sablier_url` would more likely to be an nginx location. So what about something like this ?

```nginx
location /dynamic/whoami {
      auth_request /sablier-dynamic;; # or something like this...

      proxy_pass http://whoami/$1;
    }

    location /blocking/whoami {
      auth_request /sablier-blocking; # or something like this...

      proxy_pass http://whoami/$1;
    }

location = /sablier-blocking {
   #  some config to build up the url...
}

location = /sablier-dynamic {
     # some config to build up the url...
}
```

**Comment by acouvreur** [comment]
I made a first test which would work only with the blocking strategy, but partially.

Basically I used the following sample to try it out:

*nginx.conf*
```nginx
js_import conf.d/sablier.js;

server {
    listen 80;

    subrequest_output_buffer_size 32k;

    location = / {
        auth_request /_wakeup;
        js_content sablier.hello;
    }

    location = /_wakeup {
        internal;
        js_content sablier.wakeup;                                       
    }

    location = /_is_up {
        internal;
        proxy_method      GET;
        proxy_pass_request_body off;
        proxy_pass        http://sablier:10000/api/strategies/dynamic?names=nginx-njs-whoami-1&session_duration=5m&display_name=example;
    }
}
```

*sablier.js*
```javascript
function hello(r) {
  r.return(200, "Hello world!!");
}

function wakeup(r) {
  r.subrequest("/_is_up",
    function(reply) {
      r.log(reply.responseText);
      if (reply.rawHeadersOut.find( headers => headers[0] == "X-Sablier-Session-Status")[1] == "ready") {
        r.return(200, reply.responseBuffer);
      } else {
        r.return(403, reply.responseBuffer);
      }
    }
  );
}

export default { hello, wakeup };
```

*docker-compose.yml*
```yaml
version: '3.9'

services:
  nginx:
    image: nginx:1.23.1
    ports:
      - 8080:80
    volumes:
      - ./conf:/etc/nginx/conf.d/
      - ./nginx.conf:/etc/nginx/nginx.conf

  sablier:
    image: ghcr.io/acouvreur/sablier:1.2.0
    command:
      - start
      - --provider.name=docker
      - --logging.level=trace
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  whoami:
    image: containous/whoami:v1.5.0
```

And an other config to load njs module...

But what this allows me to do is to wake up my whoami container, but it does not provide the waiting ui.

So it might work for a blocking strategy, but even though the error returned is the 403 forbidden by nginx.

```
curl localhost:8080/
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.23.1</center>
</body>
</html>
```

But this call did wake up the service via subrequest
![image](https://user-images.githubusercontent.com/22034450/205412329-7500551d-bf0a-4003-8b96-69a11741e5f7.png)
![image](https://user-images.githubusercontent.com/22034450/205412361-92540861-a44e-4c03-95ad-b55fbb4e09fd.png)

So right now, I just need to find a way to retrieve the body from the subrequest. Which is something that seems impossible to do with the auth module. See https://stackoverflow.com/questions/31431436/nginx-is-it-possible-to-get-response-retuned-from-auth-request

**Comment by acouvreur** [comment]
I just pushed a working example using njs.

Please checkout https://github.com/acouvreur/sablier/tree/feature/add-nginx-reverse-proxy-integration/plugins/nginx

You can try it out yourself.

```shell
git clone https://github.com/acouvreur/sablier
cd sablier
git checkout feature/add-nginx-reverse-proxy-integration
cd plugins/nginx
docker compose up
```

Now go to http://localhost:8080 and you should have the waiting page, and then it will automatically refresh to whoami content

**Comment by acouvreur** [comment]
Ok, there is one issue with the current state of things.

It seems that nginx resolves hosts on startup for `proxy_pass` directives, see https://github.com/docker/compose/issues/2003.

So when containers restart and so on, they'll get different ips, thus, getting some 502 unreachable no route to host in some cases. I'm investigating this issue to force reloading host.

**Comment by acouvreur** [comment]
Interesting read: https://tenzer.dk/nginx-with-dynamic-upstreams/

**Comment by acouvreur** [comment]
So, with https://github.com/acouvreur/sablier/commit/fc5d676cc24cc8e212d7c33eaddede8797c80ff5 I actually got it working with docker classic and docker swarm mode.

However, I'm not so sure how I should pursue with Kubernetes. Because I'm sure nobody writes nginx config like that on kubernetes. Thing is, I'm not used to config nginx as an ingress controller on kubernetes. I've read some guides here and there, and the guide here https://kubernetes.github.io/ingress-nginx/.

But if I could have your input @skurfuerst it would be nice, and more than that, how can I configure the ingress controller to inject the same behavior as my nginx config files for docker.
