### ISSUE TITLE
add retry strategy

### ISSUE THREAD

**Issue by tomaszduda23** [acouvreur/sablier#142]
For no browser client retry strategy could be implemented to work around https://github.com/acouvreur/sablier/issues/62. Most clients  follow https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302 so it could be use to ask client to retry connection.
```
GET domain.com -> wait 5sec -> 302 Location: trampoline1.domain.com
GET trampoline1.domain.com -> wait 5sec -> 302 Location: trampoline2.domain.com
GET trampoline2.domain.com -> wait 5sec -> 302 Location: trampoline3.domain.com
...
till endpoint up
...
GET trampoline3.domain.com -> 302 Location: domain.com
```

**Comment by acouvreur** [comment]
Well, just using curl will fail because it does not follow redirect by default.

What do you think?

**Comment by tomaszduda23** [comment]
curl is kind of exception. It fails even with `curl github.com`. Most clients would follow redirection though. It is common to use 301 for http to https redirection. Even if you sort our https://github.com/acouvreur/sablier/issues/62 some clients may timeout if there is not activity. Having more options seems to be good.

**Comment by acouvreur** [comment]
I see in your example that you have multiple subdomains, I'm not sure if I understand the reason why.

Shouldn't I redirect to itself? It's the only missing part

**Comment by tomaszduda23** [comment]
> Shouldn't I redirect to itself? It's the only missing part

Redirect to itself is better idea. I had impression that you will get error if you do so I can be wrong though.

ERR_TOO_MANY_REDIRECTS should be considered. Google says it can be from 5 - 50 redirection before a client give up.

**Comment by acouvreur** [comment]
How would you make it work with traefik ?
What kind of configuration would you do ?

**Comment by tomaszduda23** [comment]
I guess that would do.
```
  blocking:
    default-timeout: 1m
    # if set returns HTTP Status 302 when endpoint become ready or timeout to ask client to repeat connection
    max-retries: 5
```

**Comment by tomaszduda23** [comment]
Even simpler you could just let client fail with ERR_TOO_MANY_REDIRECTS.
```
  blocking:
    default-timeout: 1m
    # if set returns HTTP Status 302 when endpoint become ready or timeout to ask client to repeat connection
    retry: true
``

**Comment by acouvreur** [comment]
So, I started tackiling this again and I think I will add this config:
```
blocking:
  useRedirect: true
```

Basically on the first successful blocking request, for traefik plugin, we will redirect to itself.

For this I need to add info if the service was started with this request (otherwise the service is already up and running, no redirect)

Not really sure how to do that. I can do it with custom headers, but I also need to re-write the concurrent calls to the same service so they target the same request in the backend.
Cause if you start two blocking request at the same time, one might say it started it while not the other
