### ISSUE TITLE
services started with docker compose won't be stopped by sablier unless hit with a request first

### ISSUE THREAD

**Issue by xsolinsx** [acouvreur/sablier#153]
**Describe the bug**
I have a docker compose which starts a multitude of services, sablier is correctly configured as it is able to start/stop services as needed but (here's the bug) ONLY when the services have been hit by a request.
If I only start the services with `docker compose up -d` all services would stay up & running forever.
In order for them to be "detected" by sablier it seems I need to hit them with a request.

**Context**
 - Sablier version: 1.3.0
 - Provider: docker 23.0.5
 - Reverse proxy: traefik 2.10.1
 - Sablier running inside a container? YES

**Expected behavior**
After starting services with `docker compose up -d` Sablier should wait for the time configured in the config and then stop them without the need to hit them first with a request.

**Comment by xsolinsx** [comment]
Nice, so this is something that will be implemented in the next release right?
I will leave this open as I do not know whether you want to close this right now or when you release the next version, I will leave the decision to you 😄 
Thanks

**Comment by IzeQube** [comment]
I have just started implementing sablier with caddy and the new groups function.

Do you think it would be possible to include the function to shutdown not needed containers if they are up, but shouldn't be up because of missing requests...

**Comment by ab623** [comment]
> Hi @xsolinsx,
> 
> Without any prior request, Sablier has no way of knowing which containers to start and stop.
> 
> The beta feature of `group` using autodiscovery of containers with sablier labels could implement such feature.

On startup why cant sablier get a list of all containers with the sablier.enable label set to true, and apply the default session time to them?

I've also noticed that even through the service is up, once sablier first starts, it still shows the "waiting" screen on the first hit, even though it should bypass it as the service is up. I assume its for the same underlying reason, it hasnt built this "internal registry" of services.

**Comment by webysther** [comment]
Add healthcheck to you services fix the problem.

**Comment by ab623** [comment]
There already is a healthcheck on the service.

Currently
1. Service A comes up (showing healthy)
2. Sablier comes up
3. Wait for an hour
4. Service A is still up 

Expected
1. Service A comes up (showing healthy)
2. Sablier comes up
3. Wait for an hour
4. Sablier brings down Service A

----

> Add healthcheck to you services fix the problem or configure a status server to check.
What is a status server?

**Comment by acouvreur** [comment]
Sablier does not (yet) pick up already started services, you need to access them at least once in order for them to be downscaled.

I will probably change this behavior with anoption in the future.

**Comment by webysther** [comment]
> There already is a healthcheck on the service.
> 
> Currently
> 
> 1. Service A comes up (showing healthy)
> 2. Sablier comes up
> 3. Wait for an hour
> 4. Service A is still up
> 
> Expected
> 
> 1. Service A comes up (showing healthy)
> 2. Sablier comes up
> 3. Wait for an hour
> 4. Sablier brings down Service A
> 
> > Add healthcheck to you services fix the problem or configure a status server to check.
> 
> What is a status server?

like uptime kuma, but, nevermind, I was wrong about it.

**Comment by xsolinsx** [comment]
unstale

**Comment by ab623** [comment]
I do the same. When I restart services I have to hit them once with a request so Sablier kicks in. Not ideal.

**Comment by acouvreur** [comment]
Reviving this issue, I will create this feature but I'd like to gather some feedback here.

---

The goal is to create a startup behavior after everything has been loaded properly, workloads that have been auto-discovered (using labels), will be shutdown if they are currently running and not currently in an active session.

How would you name such option ?

- `auto-stop`
- `auto-stop-on-startup`
- `shutdown-running-discovered-workloads`
- etc.

if you have some ideas, that'd be great. I know that @gorositopablo you'd be interested by this.

**Comment by IzeQube** [comment]
I think I like `auto-stop-on-startup`.

And I am really looking forward to this new function.

**Comment by pablogorosito** [comment]
Agree, I believe that `auto-stop-on-startup` would be better.

**Comment by acouvreur** [comment]
You can try using the docker tag ` 1.8.0-beta.7`.

This is enabked **by default**. Because as you all stated, this is the behavior we'd actually expect from Sablier. And I agree.

It's not a breaking change in the way that old configurations are still valid. You can opt-out by setting `provider.auto-stop-on-startup` to false.

I'm waiting for your feedback!

**Comment by valankar** [comment]
Thanks for implementing this. Just a quick question. If I'm using `names` in my Caddyfile, I also need to set the label `sablier.enable=true` in the separate containers, correct?

**Comment by acouvreur** [comment]
> Thanks for implementing this. Just a quick question. If I'm using `names` in my Caddyfile, I also need to set the label `sablier.enable=true` in the separate containers, correct?

Yes.

Sablier needs to know which container to stop. For that, you need to add the following label `sablier.enable=true`.

You can still use `names` to target containers, there's no issue with that.

This is purely auto-discovery done by Sablier at startup, and it does not involve any reverse proxy configuration or adjustment.

**Comment by valankar** [comment]
Just tested with the beta and it works well.

**Comment by xsolinsx** [comment]
if I run twice the same `docker compose up -d` sablier only kills the containers the first time, not the second one

**Comment by deimosfr** [comment]
I confirm I have the same behavior

**Comment by acouvreur** [comment]
> if I run twice the same `docker compose up -d` sablier only kills the containers the first time, not the second one

> I confirm I have the same behavior

Can you please share a quick reproducible compose file ?

Also, with the debug log enabled, what do you see in the logs ?

One behavior of the auto-stop is to stop all containers that are currently running, but that Sablier is not aware of.

**By default, Sablier will save the current state upon shutdown.**

So upon restart, Sablier loads back your containers session from the previous run and it will not shut them down.

You can try by disabling storage completely, I think this issue won't happen again.

**Comment by valankar** [comment]
I think what they are referring to is the auto-stopping is only run at startup and not periodically. Then, if you restart your container (not the sablier one), it does not get stopped again until you make another request. i.e. The containers are stopped at "startup" of sablier only.

Perhaps it should run periodically?

**Comment by acouvreur** [comment]
> I think what they are referring to is the auto-stopping is only run at startup and not periodically. Then, if you restart your container (not the sablier one), it does not get stopped again until you make another request. i.e. The containers are stopped at "startup" of sablier only.
> 
> Perhaps it should run periodically?

The current behavior is to stop the found containers at startup only, not periodically.

I think that the desired behavior is actually to register all your containers, and have Sablier stop them for you.
If you start the container manually while Sablier is running, it will not stop it again for you.

If the current behavior does not meet your needs, maybe we can refine, change or add configuration option to get to the desired behavior.

What behaviors would you like to have ?

**Comment by valankar** [comment]
For my case, I'm happy with the current behavior. However, I can imagine the scenario described in:

https://github.com/acouvreur/sablier/issues/153#issuecomment-1999167626

For example, say you have some automatic updates of your container, or you are doing some development requiring updating it. You may be only hitting the service on an internal address and not via Sablier. Every time that happens, you'd need to access it with Sablier to have it notice the new up state.

You can of course update the image of your containers while they are stopped, which is one way around this. Perhaps others can chime in on their use case/reasoning.

**Comment by deimosfr** [comment]
> I think what they are referring to is the auto-stopping is only run at startup and not periodically. Then, if you restart your container (not the sablier one), it does not get stopped again until you make another request. i.e. The containers are stopped at "startup" of sablier only.
> 
> Perhaps it should run periodically?

Exactly the issue and behavior I expect! Check periodically would be the solution from my POV.

**Comment by valankar** [comment]
I think doing it periodically makes sense, thought we should be a bit careful on the period. Imagine a scenario where you bring up this container at the end of the time period. It will immediately get stopped.

It should probably work like:

1. Sablier detects that a container is up that should not be.
2. Sablier resets its timer for the service just as if a request has been made.
3. Container is shutdown when the timer is up.

**Comment by acouvreur** [comment]
Perhaps this feature should be some kind of "reconciliation" that could happen periodically.

I better understand the use case now.

We can maybe add this as an extra feature, and also have some opt-in/opt-out labels.

We can go further and have some labels with pre-defined hours for reconciliation. Any way, we might have w new feature here, which is not the `auto-stop-on-startup`.

From my point of view, the `startup` part of `auto-stop-on-startup` was referring to Sablier. What do you think ?

**Comment by gorositopablo** [comment]
I'm not sure about all the comments with docker-compose, but I've tried with `sablier:1.8.0-beta.7` in Kubernetes with Traefik and the containers are only terminated at Sablier boot up.

So, let's say that I:
1- Deploy Sablier
2- Deploy my workload (using labels)
3- Nothing happens
4a- restarting Sablier it kill the pod, or (new behavior with `sablier:1.8.0-beta.7`)
4b- making a request to the backend, it kill the pod. (classic behavior)


While Sablier does kill the pod at the start of its lifecycle, it means that I need to restart Sablier each time that I have a new release.


Thanks @acouvreur

**Comment by deimosfr** [comment]
Good Idea @acouvreur  . I think we can start simple without specific hours and add it later if requested? I personaly don't have this need

**Comment by Maypul** [comment]
@acouvreur would be possible to implement also periodic check on services? I sometimes update my services and forget to restart Sablier itself so these services keep running until someone logs on them. I would love to see a feature that Sablier checks periodically for services to see if they are running and stop them if there are no active requests.

**Comment by OBoudreaux** [comment]
> From my point of view, the `startup` part of `auto-stop-on-startup` was referring to Sablier. What do you think ?

Could this establish a race condition? Thinking about a docker stack, if sablier is one of many containers it will only stop containers that have spun up before it has.

Perhaps `auto-stop-on-startup-delay` option that the user can specify some number of seconds after Sablier start up would be a solution?
