### ISSUE TITLE
Create Docs Website

### ISSUE THREAD

**Issue by acouvreur** [acouvreur/sablier#155]

**Comment by acouvreur** [comment]
You can preview the doc website here: https://acouvreur.github.io/sablier

Feedback is welcomed!

**Comment by webysther** [comment]
Hey, looks great, I read everything, maybe a guide for nginx+docker+blocking because I got stuck on this part: https://acouvreur.github.io/sablier/#/plugins/nginx?id=configure-the-plugin

**Comment by webysther** [comment]
This look very nice and have less move parts:

![image](https://github.com/acouvreur/sablier/assets/750007/e4860d8b-665c-4e3e-a981-201d1bc6c36e)

But don't get covered in the docs.
