### ISSUE TITLE
DynamicStrategy RefreshFrequency is hardcoded to 5s

### ISSUE THREAD

**Issue by patcher-ms** [acouvreur/sablier#175]
**Describe the bug**
I noticed that if even if change the refresh frequency in the configuration the template refreshes after 5 seconds. I believe this is due to this value being hardcoded to 5s https://github.com/acouvreur/sablier/blob/5ab29c3cccef91ae8dd0406da88549b636beb79d/app/http/routes/strategies.go#L90

**Context**
 - Sablier version: [e.g. 1.4.0-beta.4]
 - Provider: [e.g. docker]
 - Reverse proxy: [e.g. traefik v3.0]
 - Sablier running inside a container? Yes

**Expected behavior**
I would expect that changing Sablier's configuration
```yaml
strategy:
  dynamic:
    default-refresh-frequency: 1s
```
or setting the refresh frequency in a label (e.g. `traefik.http.middlewares.grafana.plugin.sablier.dynamic.refreshFrequency=10s`) would result in a response with the refresh frequency I configured.

**Additional context**
All the other values I configured are picked up correctly so I don't this this is a misconfiguration on my side.
I am not using health checks on the Docker container which could hide the issue since an health check would prevent a pod from being detected as up until the service is actually ready.

**Comment by acouvreur** [comment]
Will look it up, seems easy to fix

**Comment by patcher-ms** [comment]
Thanks for looking into this so quickly.

Unfortunately I am still having a couple issues:
- the value used in https://github.com/acouvreur/sablier/pull/176 comes from https://github.com/acouvreur/sablier/blob/98f0f81894b7c724590df19ef89e94c15c4bbb92/app/http/routes/strategies.go#L53, which only looks at `DefaultRefreshFrequency` and not on the custom configuration coming from the label
- there is a discrepancy between the [sample configuration](https://github.com/acouvreur/sablier/blob/98f0f81894b7c724590df19ef89e94c15c4bbb92/sablier.sample.yaml#L18) and the [yaml decoding definition](https://github.com/acouvreur/sablier/blob/98f0f81894b7c724590df19ef89e94c15c4bbb92/config/strategy.go#L9) the former says the config value is `default-refresh-frequency` but the latter tries to decode `yaml:"defaultRefreshFrequency"`

**Comment by acouvreur** [comment]
I'll take a look, but the value should be retrieved from the configuration first as a default value, but then should overwritten by the payload
