### ISSUE TITLE
Add SWAG reverse proxy integration

### ISSUE THREAD

**Issue by EmberLightVFX** [acouvreur/sablier#203]
**Describe the reverse proxy you'd like**
LinuxServer.io's reverse proxy SWAG is getting bigger and bigger and with included Fail2Ban + CrowdSec plugin it's the reverse proxy that me and many others have picked for ease to setup and security.
It takes care of your certs and your ddns etc. A really powerful reverse proxy.

**Does the reverse proxy provides middleware/module/extension support**
SWAG have a plugin/mod system, all open source, so the sablier implementation could be a simple mod. You can find the CrowdSec plugin here to see how it's build up: https://github.com/linuxserver/docker-mods/tree/swag-crowdsec

**Additional context**
You can find more info about SWAG here: https://docs.linuxserver.io/general/swag

**Comment by acouvreur** [comment]
Dupliacte of #110

**Comment by acouvreur** [comment]
Unstale

**Comment by acouvreur** [comment]
Unstale, issues will now be considered stale after a much longer peeiod of time

**Comment by acouvreur** [comment]
Closing if favor of https://github.com/acouvreur/sablier/issues/110
