### ISSUE TITLE
scaling down to zero does not work the first time

### ISSUE THREAD

**Issue by tomaszduda23** [acouvreur/sablier#23]
Scaling down to zero does not work if there was no http request to the service at all. E.g. during creating the cluster all pods stay up. After first http request the deployment is scale down to zero.

**Comment by acouvreur** [comment]
Yes, you should create a deployment with 0 replicas. As it acts as a middleware and not a manager.

**Comment by tomaszduda23** [comment]
I got it. Thanks
Maybe it would be worth to mentioned this in doc and examples https://github.com/acouvreur/traefik-ondemand-plugin/blob/main/examples/kubernetes/deploy-whoami.yml

**Comment by tomaszduda23** [comment]
It cause another problem. If pod is deploy again when it is up. It scale to 0 and it is not scale up to 1.
