### ISSUE TITLE
Suspend cronjobs

### ISSUE THREAD

**Issue by hijak** [acouvreur/sablier#230]
hi

i am testing sablier for an environment with cronjobs. are there any plans to integrate cronjob scheduling so they can be suspended as well?

**Comment by acouvreur** [comment]
Could you please give more details ?

Are these regular cron ?

Are you referencing [Kubernetes CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) ?

What is your use case and how would you like Cron Jobs to be supported ?

**Comment by acouvreur** [comment]
Right now Sablier works through reverse proxies, so cron jobs wont be able to "wake up" the deployment internally I'm afraid.
