### ISSUE TITLE
Parameter to set individual loading.go page refresh time

### ISSUE THREAD

**Issue by dariuszszyc** [acouvreur/sablier#27]
I am testing the beta functionality to start/stop several containers. 
I have to start 3 containers, which scale up quick, but take some time to fully load.
Until that time - the loading page quickly disappears and shows "Bad request" which is visible until everything is fully loaded.

I know that this specific container (and its dependencies) - needs 15 seconds to to be fully loaded.
Would be great if we could provide (similar to "displayname") parameter where we could se the refresh time - separately for each middleware. I'd keep "5" as a default value.

Thanks for developing this great plugin!

**Comment by acouvreur** [comment]
Thanks for the suggestion.

If your container has an healthcheck, the service will use it to determine if it should send data to it.

In most cases, this will be more efficient and more precise.

More than that, you can actually create a custom page with the refresh rate that you desire  https://github.com/acouvreur/traefik-ondemand-plugin#custom-loadingerror-pages

> You must include `<meta http-equiv="refresh" content="5" />` inside your html page to get auto refresh.
