### ISSUE TITLE
`[Kubernetes]` Helm Chart ? 

### ISSUE THREAD

**Issue by DrummyFloyd** [acouvreur/sablier#271]
**Describe the provider**
Dunno where i should make this PR
the idea, is to make the deployement easier on Kuberneetes => btw it's not very user friendly =/ had to dig a bit into PRs/Docs and readme to make it works 

but once i got all needed info, everything work like charm

So the ticket it's related to this 
=> do you want a Helm chart for sablier with few test ? (helm unittest)

if yes=> do you have some api Healthcheck for readyness/liveness probe (do not look yet into the code for that )

Merci pour ton Boulot, => de la part d'une startup de Sophia ;)

**Comment by chkpwd** [comment]
What proxy are you using on your k8s cluster? I see nginx is still not supported.

**Comment by DrummyFloyd** [comment]
@chkpwd 
i use traefik for the moment

**Comment by gtherond** [comment]
Any improvement on this? I'll be thrilled to use a helm-chart rather than having to maintain my own whole deployment set of manifests.

**Comment by acouvreur** [comment]
Hey, I'll be working on this soon :)
I'm working on making the github pages behaving as a chart repo

**Comment by gtherond** [comment]
aaaaah cool! Very nice!

**Comment by acouvreur** [comment]
Hello everyone, as mentioned I will be moving this to a new organization. So I've actually baked the helm chart: https://github.com/sablierapp/helm-charts

You can start testing it! I'm sure there will be some issues but it's a first :)
