### ISSUE TITLE
Preview Images Broken on Docs

### ISSUE THREAD

**Issue by cf-sewe** [acouvreur/sablier#276]
**Describe the bug**
The [preview images](https://acouvreur.github.io/sablier/#/themes?id=the-embedded-themes) are broken on the documentation page.

<img width="1145" alt="image" src="https://github.com/acouvreur/sablier/assets/52649758/f255078b-942f-49a2-a7f0-c62bf9ddfb50">

**Comment by acouvreur** [comment]
Thanks for the feedback! I'll fix the broken links
