### ISSUE TITLE
Enhance Theme support

### ISSUE THREAD

**Issue by acouvreur** [acouvreur/sablier#278]
The theme support is currently not optimized as the whole template is parsed on every request.

Themes should be loaded on startup into memory and that's it.

This will prevent a lot of potential security issues, but also prevent you from live editing themes.

Instead, a dedicated endpoint may be created for that purpose in a future release.

**Comment by CodeBradley** [comment]
@acouvreur Can you share how themes can be customized? I don't remember seeing this anywhere and I can't sh into the container
