### ISSUE TITLE
Docker Swarm Provider Panic error 

### ISSUE THREAD

**Issue by evmolpos** [acouvreur/sablier#279]
Trying to start Sablier using either v1.6.0, main or beta tagged images, docker swarm service containers exit with error:

INFO[0000] (version=main, branch=main, revision=b0b7981e9ef07230cfc051a110a5b6f68e459b2d) 
panic: unimplemented provider docker_swarm
-- or --
INFO[0000] (version=beta, branch=beta, revision=052f7db91f954bc45921562a5d354f27fae27698) 
panic: unimplemented provider docker_swarm
-- or --
INFO[0000] (version=1.6.0, branch=HEAD, revision=381cdd7fe9583688daf0873bcbc58a4ddc47d0df) 
panic: unimplemented provider docker_swarm

Can someone point me what I'm probably missing ?

**Context**
 - Sablier version: 1.6.0, beta, main
 - Provider: Docker Swarm Server Version: 26.0.1
 - Reverse proxy: Traefik 2.11.2
 - Sablier is running inside a container

**Expected behavior**
Expected PROVIDER_NAME=docker_swarm or --provider.name=docker_swarm as acceptable provider

**Additional context**
Docker compose declaration file is used to apply docker swarm sablier service.
Docker Swarm Daemon is SSL protected.

**Comment by acouvreur** [comment]
Hey @evmolpos !

Thank you for your issue, can you try with `swarm` instead ?

The doc is not synced with the actual code, I'll add a more descriptive error with the supported values and update the documentation.

Thanks!

**Comment by prologic** [comment]
Cool! 👌 I'll have to try this out 🤞

**Comment by evmolpos** [comment]
thanks I,ll try using 1.6.1 and report back asap !

**Comment by evmolpos** [comment]
Thanks @ acouvreur. Confirmed it works now.
PROVIDER_NAME=swarm is the value to go for Docker Swarm installations.
