### ISSUE TITLE
Support for docker-socket-proxy

### ISSUE THREAD

**Issue by thielj** [acouvreur/sablier#287]
Hi,

can you add support for controlling docker through a network proxy, instead of requiring direct access to the socket, please? Similar to what setting `DOCKER_HOST` or using docker -H `<endpoint>` would do.

For example, through a configuration setting like this:

```
    endpoint: "unix:///var/run/docker.sock"     # Default, listen to the UNIX Docker socket
    #endpoint: "tcp://docker-socket-proxy:2375"   # Use a network proxy instead
```

Ideally, this would be configurable per service or middleware, which would allow managing a containers on different hosts.

See https://github.com/Tecnativa/docker-socket-proxy and https://flast101.github.io/docker-privesc/ for some background info.

**Comment by acouvreur** [comment]
Hello!

Yes the library is configured to support all environnement variables.
Yes we could add it to the docs!

**Comment by Sblop** [comment]
Hi. While this works, the sablier container now runs at 100% CPU. Logs doesnt assist.

**Comment by acouvreur** [comment]
Closing this in favor of #272
