### ISSUE TITLE
Container name matching is not exact and also matches containers that only include the term

### ISSUE THREAD

**Issue by teun95** [acouvreur/sablier#30]
A stack with the following containers will not work with the plugin only used for _nocodb:_

- nocodb
- nocodb_mariadb

It will result in the error:

```
backend-ondemand-1  | time="2022-08-31T16:02:20Z" level=error msg="multiple containers (2) with name nocodb were found:
```

When renaming the containers to the following, the error is resolved:

- nocodb
- NOCODB_mariadb

**Comment by teun95** [comment]
I see now that this has already been noted in a previous issue

https://github.com/acouvreur/traefik-ondemand-service/blob/1e69a5754faa41bf5a7bc12feed55f48c0924077/pkg/scaler/docker_swarm.go#L95

> This is because it filters like a contain, not word match.

_Originally posted by @acouvreur in https://github.com/acouvreur/traefik-ondemand-plugin/issues/19#issuecomment-1076454187_

**Comment by acouvreur** [comment]
Do you think we should filter on the results if it contains more than one ?

**Comment by acouvreur** [comment]
It is now set to strict mode
