### ISSUE TITLE
Ondemand container is not setting the variables I inject at docker run

### ISSUE THREAD

**Issue by zenkraker** [acouvreur/sablier#32]
Hi, 
 
 I tried to deploy your docker image for onDemand but when I pass the variable to disable the swarmMode I always get swarmMode true in the logs. 
I paste the following command I used to deploy your image:

docker run -d --name='ondemand' --net='xxx' -e TZ="Europe/Berlin" -e 'swarmode'='false' -e 'swarmMode'='false' -e 'kubernetesMode'='true' -e '--swarmMode'='false' -e '--swarmode'='false' -l net.unraid.docker.managed=dockerman 
-l 'traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.name'='radarr' 
-l 'traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.serviceUrl'='http://ondemand:10000' 
-l 'traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.timeout'='1m' 
-l 'traefik.http.services.ondemand.loadbalancer.server.port'='10000' 
-l 'traefik.enable'='true' 
-p '10000:10000/tcp' 
-v '/var/run/docker.sock':'/var/run/docker.sock':'rw' 
-v '/mnt/user/appdata/ondemand':'/storagePath':'rw' 'acouvreur/traefik-ondemand-service:latest'

**Comment by acouvreur** [comment]
This is because you should be using arguments and not env var.
Just like this: 

```
docker run -v /var/run/docker.sock:/var/run/docker.sock -p 10000:10000 ghcr.io/acouvreur/traefik-ondemand-service:latest --swarmode=true
```

But as I see that you are using labels, you should create a service instead.

For this I recommend you to lookout for example here: https://github.com/acouvreur/traefik-ondemand-plugin/blob/main/examples/docker_swarm/docker-stack.yml
