### ISSUE TITLE
kind_namespace_name_replicas error from release 1.8.0-beta.9

### ISSUE THREAD

**Issue by gorositopablo** [acouvreur/sablier#354]
**Describe the bug**

It seems like a bug was introduced from release `1.8.0-beta.9` as after that version, Sablier is no longer able anymore to terminate pods in Kubernetes and in the logs this is the message:

```
level=warning msg="error stopping : invalid name should be: kind_namespace_name_replicas"
```

**Context**
 - Sablier version: [1.8.0-beta.9] and [1.8.0-beta.10]
 - Provider: [e.g. kubernetes 1.28.10]
 - Reverse proxy: [e.g. traefik v3.0.0]
 - Sablier running inside a container? yes

**Expected behavior**
Sablier should be able to terminate pods as before.

**Comment by acouvreur** [comment]
Can you show me more details on your configuration calling Sablier ?

I will push a change that shows the faulty value.

**Comment by acouvreur** [comment]
I can reproduce the issue, currently working on a fix.

**Comment by acouvreur** [comment]
Version  1.8.0-beta.12 should fix everything.

**Comment by gorositopablo** [comment]
Sorry for my delay in this input @acouvreur, I just wanted to confirm that the release `1.8.0-beta.12` works perfectly. Thanks a lot.
