### ISSUE TITLE
"error stopping : Error response from daemon: page not found" with latest beta

### ISSUE THREAD

**Issue by valankar** [acouvreur/sablier#356]
**Describe the bug**
I noticed my docker containers are not being stopped after updating to latest beta. The error logs show:

```
time="2024-07-09T08:03:38Z" level=warning msg="error stopping : Error response from daemon: page not found"
time="2024-07-09T16:32:51Z" level=warning msg="error stopping : Error response from daemon: page not found"
time="2024-07-09T18:24:50Z" level=warning msg="error stopping : Error response from daemon: page not found"
time="2024-07-09T19:49:59Z" level=warning msg="error stopping : Error response from daemon: page not found"
```

I believe it was working fine with 1.8.0-beta.7.

**Context**
 - Sablier version: v1.8.0-beta.10
 - Provider: Docker version 27.0.3, build 7d4bcd8
 - Reverse proxy: Caddy
 - Sablier running inside a container? Yes. I'm using tag `beta`

**Expected behavior**
Containers stopped after timeout.

**Comment by acouvreur** [comment]
Seeing something like page not found looks like some call is not registered on your daemon.

Are you using a socket proxy ?

**Comment by valankar** [comment]
Nope. Also I switched to the non beta and it works fine again.

**Comment by acouvreur** [comment]
Ok thanks for the quick feedback.
Can you please share me your config and more contextual logs, when is this happening ?

**Comment by acouvreur** [comment]
I think it's related to https://github.com/acouvreur/sablier/issues/354

**Comment by valankar** [comment]
Hi I just tried 1.8.0-beta.11 and I get the same issue:

```
ctime="2024-07-10T17:13:32Z" level=info msg="(version=1.8.0-beta.11, branch=HEAD, revision=f9266d6885e59ea31f200ec66b4418bc4a4c79fc)"
time="2024-07-10T17:13:32Z" level=info msg="using provider \"docker\""
time="2024-07-10T17:13:32Z" level=info msg="initialized storage to /etc/sablier/state.json"
time="2024-07-10T17:13:32Z" level=info msg="Stopping all unregistered running instances"
time="2024-07-10T17:13:32Z" level=info msg="server listening :10000"
...
time="2024-07-10T18:48:17Z" level=warning msg="error stopping : Error response from daemon: page not found"
```

I'm using this docker compose:

```
  sablier:
    image: acouvreur/sablier:beta
    container_name: sablier
    restart: unless-stopped
    command:
      - start
      - --provider.name=docker
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
```

And I'm using Caddy with simple setup such as:

```
mydomain {
        route {
                sablier http://sablier:10000 {
                        names accounts
                        session_duration 1h
                        dynamic
                }
                reverse_proxy accounts:8050
        }
}
```

Perhaps there is some flag to increase logging I could try?

**Comment by acouvreur** [comment]
I will mark al of these release as faulty. And work on increasing test reliability.

Basically, e2e tests cover everything except shuting down the instances...

**Comment by valankar** [comment]
FWIW, I added trace logging. It only added an additional line:

```
time="2024-07-10T19:44:42Z" level=debug msg="stopping ..."
time="2024-07-10T19:44:42Z" level=warning msg="error stopping : Error response from daemon: page not found"
```

**Comment by acouvreur** [comment]
Version  1.8.0-beta.12 should fix everything

**Comment by valankar** [comment]
> Version 1.8.0-beta.12 should fix everything

Yes looks like it is working. Thanks.
