### ISSUE TITLE
Feature Request: Change strategy based on endpoint

### ISSUE THREAD

**Issue by Glich440** [acouvreur/sablier#376]
Is there a way for all requests to use the dynamic strategy except if they're going to the /api endpoint?

**Comment by acouvreur** [comment]
You should be able to create two different routes using your reverse proxy.
Then define the proper middleware on each route.

The Sablier middleware does not make decision based on the route or anything else.

If your this cannot be solved using two routes, please explain your setup in detail as why you cannot do that.

Thanks! 😀

**Comment by Glich440** [comment]
after actually using sablier I realized how to actually do that, thanks for the help!
