### ISSUE TITLE
Blocking startegy is not working with Kubernetes on Traefik - 503 Service Unavailable

### ISSUE THREAD

**Issue by acouvreur** [acouvreur/sablier#62]
The Blocking Strategy intercepts the incoming request to a non existent service.

Which we allow in Traefik with the flag --allowEmptyServices on the provider. (Either Swarm or Kubernetes).

But it seems that, since the request is created without a specific endpoint to reach as it doesn't exist yet, even if Sablier ensures that the service is created, with an endpoint reachable.

This is probably because the request is already at the middleware level that the service destination cannot be modified anymore, except if you launch a new request.

I have no idea how to fix that on Traefik, I'd have to find in the Traefik repo where they create such request.

Note that it works on docker classic. Probably because it is set inside a static configuration.

See https://github.com/acouvreur/sablier/actions/runs/3242670189/jobs/5316271973#step:7:172
```
--- FAIL: Test_Blocking (0.00s)
    printer.go:54: GET http://localhost:8080/blocking/whoami
    reporter.go:23: 
        	Error Trace:	/home/runner/work/sablier/sablier/e2e/reporter.go:23
        	            				/home/runner/work/sablier/sablier/e2e/chain.go:21
        	            				/home/runner/work/sablier/sablier/e2e/response.go:585
        	            				/home/runner/work/sablier/sablier/e2e/response.go:151
        	            				/home/runner/work/sablier/sablier/e2e/e2e_test.go:39
        	Error:      	
        	            	expected status equal to:
        	            	 "200 OK"
        	            	
        	            	but got:
        	            	 "503 Service Unavailable"
        	Test:       	Test_Blocking
FAIL
FAIL	github.com/acouvreur/sablier/e2e	0.009s
FAIL
```

**Comment by acouvreur** [comment]
Original issue: https://github.com/acouvreur/traefik-ondemand-service/issues/24

**Comment by acouvreur** [comment]
Swarm is fixed

Kubernetes is not for Blicking strategy

**Comment by altitude1326** [comment]
@rtribotte could you please help on this problem ?

**Comment by rtribotte** [comment]
Hello @acouvreur @altitude1326,

I have to say that I'm not familiar with Sablier.
At a glance, I can confirm that the "503 Service Unavailable" status is indeed returned when reaching an empty server load balancer, which can happen when using the `allowEmptyServices` option.

> This is probably because the request is already at the middleware level that the service destination cannot be modified anymore, except if you launch a new request.

Depending on what you mean here, once a request has matched a router's conditions, is entered in it, and is passing through the middleware chain, it is true that the only service that could be reached is the one attached to the router. Besides, the actual server that is reached depends on the load balancer state and kind.

It is important to note that once the request has entered a router, and hence a middleware/plugin chain leading to a service, no matter how much time the request is retained in the plugin until the service is ready, the service load balancer will never be updated if the configuration is reloaded.
This means that when the Kubernetes service becomes ready, Traefik will generate and apply a new routing configuration, and create a new router that will replace the previous one for new incoming requests.

So, if the plugin retains requests while waiting for the service readiness, when it is ready,  the request is finally reaching the empty load balancer (that has not changed, event though Traefik is aware of the new state of the service and has built a new router/service for it).

The only way (but ugly) to reach the updated service would be to loop back by making the request on Traefik again.

Hope this help to better understand what is probably happening here.

**Comment by altitude1326** [comment]
Thanks a lot @rtribotte it's crystal clear now, but too bad because it means that sablier will never be able to work on kubernetes in a satisfactory way in "blocking mode".
Is it a good idea to propose a change request on the treafik github to modifythe operation in order to address this problem or does it make no sense for you ?

**Comment by rtribotte** [comment]
> Is it a good idea to propose a change request on the treafik github to modifythe operation in order to address this problem or does it make no sense for you ?

Well, the Traefik project is always open to contributions and we would gladly welcome a proposal issue to discuss the problem and the potential solutions.

Nevertheless, I would say that there are several options here:

1. Redirect the request, to make the client redo the request, which, after Sablier made sure the services are ready, will reach healthy services.

2. Have two chained Traefik instances, the front one with Sablier, and the second one discovering and handling the routing to the services.

3. In Kubernetes, add the ability for Traefik to rely on Service IPs. The Kubernetes load balancer will be updated and ready to route the request to services, once Sablier releases it.

4. Rework the core of Traefik to have services updated even on runtime routers. (It could be suggested, but this is an impacting change, and it would require quite some time to be evaluated.)

**Comment by rtribotte** [comment]
I forgot to mention:

5. Use an external name service that points to the DNS name of the actual service managed by Sablier. This way the Traefik service is only aware of that external name service and the request, when released by Sablier, should reach the Kubernetes service.

**Comment by gorositopablo** [comment]
> I forgot to mention:
> 
>     5. Use an external name service that points to the DNS name of the actual service managed by Sablier. This way the Traefik service is only aware of that external name service and the request, when released by Sablier, should reach the Kubernetes service.


This should be part of the documentation of Kubernetes integration maybe. 
I thought Sablier didn't work with blocking in Kubernetes but this workaround fixed it like a charm. 

It works well with blocking now. Thanks for the info provided @rtribotte 

I just want to leave the comment for future reference in case someone arrives here.
